apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
  - host: "blob.kube.local"
    http:
      paths:
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: cluster-ip
            port:
              number: 80