apiVersion: v1
kind: Pod
metadata:
  name: pod-proba
  labels:
    component: konexioa
spec:
  containers:
    - name: blobcity
      image: "store/blobcity/db:1.7.10"
      ports:
        - containerPort: 10113
        - containerPort: 10111
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
      volumeMounts:
        - name: vol
          mountPath: /data
  volumes:
  - name: vol
    persistentVolumeClaim:
      claimName: pvc-datuak